version: "3.5"
services:
    modeldb-backend:
        image: modeldb-backend:latest
        container_name: "modeldb-backend"
        build: .
        expose:
            - "8085"
        ports:
            - "8085:8085"
        networks:
            - modeldb_network
        environment:
            - VERTA_MODELDB_CONFIG:/config/config.yaml
        volumes:
            - /path/to/modeldb-backend:/config

    backend-proxy:
        image: backend-proxy:latest
        container_name: "backend-proxy"
        expose:
            - "8080"
        ports:
            - "8080:8080"
        depends_on:
            - modeldb-backend
        networks:
            - modeldb_network

    uacservice:
        image: uacservice:latest
        container_name: "uacservice"
        expose:
            - "50051"
        ports:
            - "50051:50051"
        depends_on:
            - redis-cache
        networks:
            - modeldb_network
        environment:
            - CONFIG_DIR:/config
        volumes:
            - /path/to/UACService:/config

    uacservice-proxy:
        image: uacservice-proxy:latest
        container_name: "uacservice-proxy"
        expose:
            - "8051"
        ports:
            - "8051:8051"
        depends_on:
            - uacservice
        networks:
            - modeldb_network

    webapp:
        image: webapp:latest
        container_name: "webapp"
        expose:
            - "80"
        ports:
            - "3000:80"
        depends_on:
            - uacservice-proxy
            - backend-proxy
        networks:
            - modeldb_network

    redis-cache:
        image: redis:latest
        container_name: "redis-cache"
        expose:
            - "6379"
        ports:
            - "6379:6379"
        networks:
            - modeldb_network

networks:
  modeldb_network:
    # external:
    #   name: modeldb_network

volumes:
  mongodata:
