apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modeldb
  name: modeldb-frontend
spec:
  selector:
    matchLabels:
      app: modeldb
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modeldb
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.image.modeldbWebappImage}}
        imagePullPolicy: Always
        name: modeldb-frontend
        env:
          - name:  DEPLOYED
            value:  "yes"
          - name: BACKEND_API_PROTOCOL
            value: "http"
          - name: BACKEND_API_DOMAIN
            value: "modeldb-backend-proxy:8080"
        ports:
        - containerPort: 3000
