apiVersion: v1
kind: Service
metadata:
  annotations:
  name: modeldb-postgres-backend
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: modeldb
    tier: postgres
  type: ClusterIP
